### ISSUE TITLE
date time picker needs to accept a selection property/value

### ISSUE THREAD

**Issue by d-ashfield** [ciena-frost/ember-frost-date-picker#72]
date time picker needs to accept an input selection property/value
This is becoming a blocking issue in the mcp provisioning forms, where we need to use bunsen conditionals that force a re-render on the forms.  When a re-render occurs the time is being reset back to the defaults of 'Now' or 'Never'.

**Comment by notmessenger** [comment]
The `frost-date-time-picker` already has the ability to have a value set on it, as demonstrated in the demo app at:

_https://github.com/ciena-frost/ember-frost-date-picker/blob/master/tests/dummy/app/pods/experiments/template.hbs#L42_
and
_https://github.com/ciena-frost/ember-frost-date-picker/blob/master/tests/dummy/app/pods/experiments/controller.js#L9_

**Comment by sophypal** [comment]
Apologies @d-ashfield. I had thought that this component had the selection group but it was actually just the `when` renderer in bunsen.
