### ISSUE TITLE
The date-time-picker defaults to the current date and time

### ISSUE THREAD

**Issue by jscharf** [ciena-frost/ember-frost-date-picker#98]
# BUG REPORT

* [x] I have ensured that the issue isn't already reported
* [x] I have confirmed that the issue is reproducible with the latest released version
* [x] I have deleted the **FEATURE REQUEST / CODE CHANGE** section

## Summary
* The date-time-picker defaults to the current date and time

## Expected Behavior
* The date-time-picker should not have a default value

## Actual Behavior
* Instead of being blank when the value is undefined, the date-time-picker displays the current time
* I'm expecting the date-time-picker to be blank with a undefined value, just like the date-picker

## Possible Solution
* Allow the date-time-picker to be blank when an undefined value is passed to it

## Context
* At Ciena, this issue has create a User Experience problem because users do not think the value is cleared when they click the clear button beside the date-time-picker
* The context for this issue when the date-time-picker is used in a facet panel inside of an object browser, and the user is unable to clear the value from the facet

## Environment

(answer all that are applicable)

* [x] I am using the latest released version (can check with `npm ls <package-name>`)
* I am using these browsers:
  * [x] Latest Chrome
  * [ ] Latest Firefox
* [x] My version of `Node` is: 10.5.0
* [x] My version of `npm` is: 6.1.0
* [ ] My OS is:
* [ ] Include the contents of your _package.json_ file

**Comment by jscharf** [comment]
@notmessenger do you any context or history around why the date-time-picker defaults to the current date and time instead of just a blank field?

**Comment by notmessenger** [comment]
@jscharf I do not
